### ISSUE TITLE
allow setting the ndk version

### ISSUE THREAD

**Issue by mmmries** [boxen/puppet-android#13]
I have an app that requires ndk r10, but currently this module sets <code>$android::config::ndk_version</code> to [r9c-boxen1](https://github.com/boxen/puppet-android/blob/004cdedf207a524ac9f35b99330c77c39179e85c/manifests/config.pp#L6).

I'm a bit of a puppet noob so I'm not sure I can help out much with the pull request. But I'll give it a shot if you can point me in direction of an example I can follow.

**Comment by mmmries** [comment]
can we tag a new version that includes this fix? `1.3.1`?

**Comment by blackjid** [comment]
you mean this fix right?? https://github.com/boxen/puppet-android/commit/d7ce09a0f0748cdf7c603725c1880feb48003a52

**Comment by blackjid** [comment]
https://github.com/boxen/puppet-android/releases/tag/1.3.1

**Comment by mmmries** [comment]
@blackjid yes that is what I meant. Thanks again!
